.TH "elegance-colors" 1 "12-07-2012" elegance-colors "User Manual"

.SH NAME
elegance-colors \- chameleon theme for gnome shell

.SH SYNOPSIS
.B elegance-colors
[options...]

.SH DESCRIPTION
Elegance Colors is a highly customizable chameleon theme for Gnome Shell. It can change colors according to the current GTK theme, current wallpaper (uses imagemagick to get color) or use a user defined color.

.SH OPTIONS
.TP
.BR start
Start the process in foreground

.TP
.BR stop
Stop the running process

.TP
.BR apply
Apply the configuration

.TP
.BR update
Update config file to include new options

.TP
.BR export\ /path/to/themefile.zip
Export the current theme to a zip file

.SH CUSTOMIZATION
A process runs in background which detects changes, generates the theme and reloads the theme accordingly. After installation, you must run the following command to start the background process,

.B elegance-colors

To set the theme, run the following commands,

.B gsettings set org.gnome.shell.extensions.user-theme name 'elegance-colors'

You can launch the GUI from the menu which lets you customise various aspects of the the theme. You can also export your customized theme, import/export settings from the GMenu. Click on the title in the Gnome Shell top bar to get the GMenu.

.SH FILES

The configuration file is
.B ~/.config/elegance-colors/elegance-colors.ini

Presets are located under
.B ~/.config/elegance-colors/presets/

Temporary files are created under
.B /tmp/elegance-colors/

.SH NOTES
The configuration file should not be edited by hand to avoid potential errors.

.SH CAVEATS
When applying the new configuration, the theme is reloaded, and Gnome Shell may freeze if you do things really fast while reloading the theme.

.SH SEE ALSO
https://github.com/satya164/elegance-colors

.SH AUTHOR
Satyajit Sahoo <satyajit.happy@gmail.com>
